version: '2.4'
services:
  nginx:
    build:
      context: ./nginx
    ports:
    - 8080:80
  doh-proxy:
    build:
      context: ./doh-proxy
    command: "--upstream-resolver 1.1.1.1 --level DEBUG"
  pihole:
    image: pihole/pihole
    env_file: .env
    ports:
    - 8082:80